# Generated by Django 4.0.1 on 2022-01-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
