# Generated by Django 4.0.1 on 2022-01-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_signup_email_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
