# Generated by Django 4.0.1 on 2022-01-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_signup_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile_pic',
            field=models.ImageField(default='exit', upload_to='image/'),
            preserve_default=False,
        ),
    ]
