# Generated by Django 4.0.1 on 2022-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_signup_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
